diff_drive_controller:
  ros__parameters:
    linear.x.max_velocity: 0.06
    linear.x.min_velocity: -0.06
    linear.x.max_acceleration: 0.02
    linear.x.max_deceleration: -0.04
    angular.z.max_velocity: 0.3
    angular.z.min_velocity: -0.3
    angular.z.max_acceleration: 0.15
    angular.z.max_deceleration: -0.3
