'use strict';
const $=id=>document.getElementById(id), client=sessionStorage.consoleClient||(sessionStorage.consoleClient=(crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join(''))), held=new Set();
let state={},points=[],scenePose=null, cameraVisible=true,armBusy=false,cmdBusy=false,seq=Number(sessionStorage.consoleSeq||0),lastV=0,lastW=0,lastMessage=0;
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);lastMessage=Date.now()}
async function api(path,data={}){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,client}),signal:AbortSignal.timeout(path==='arm'?25000:12000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Ошибка запроса');return j}
function moving(){const speed=Number($('speed').value)/100;return [((held.has('forward')?1:0)-(held.has('back')?1:0))*speed,((held.has('left')?1:0)-(held.has('right')?1:0))*.3]}
function nextSequence(){seq=Math.max(seq+1,Date.now()*1000);sessionStorage.consoleSeq=String(seq);return seq}
async function sendCommand(force=false){const [v,w]=moving();if(!state.active||state.owner!==client)return;if(cmdBusy&&!force)return;if(!force&&!v&&!w&&!lastV&&!lastW)return;cmdBusy=true;lastV=v;lastW=w;try{await api('cmd',{v,w,seq:nextSequence()})}catch(e){if(Date.now()-lastMessage>2500)message(e.message,true)}finally{cmdBusy=false}}
function neutral(){held.clear();highlight();sendCommand(true)}
function highlight(){document.querySelectorAll('[data-dir]').forEach(b=>b.classList.toggle('pressed',held.has(b.dataset.dir)))}
async function stop(){held.clear();lastV=lastW=0;highlight();state.active=false;try{await api('stop');message('STOP зафиксирован. Для продолжения снова включи привод.')}catch(e){message('Нет ответа от GUI. Открой отдельный STOP по ссылке сверху.',true)}}
$('stop').onclick=stop;$('neutral').onclick=neutral;
$('arm').onclick=async()=>{if(armBusy)return;neutral();armBusy=true;$('arm').disabled=true;message('Проверяем оси и питание, включаем привод…');try{await api('arm');message('Привод включён. Удерживай стрелки или WASD; Esc — STOP.')}catch(e){message(e.message,true)}finally{armBusy=false;$('arm').disabled=false}};
const keymap={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
window.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();stop();return}if(/INPUT|TEXTAREA/.test(document.activeElement.tagName))return;const d=keymap[e.code];if(d){e.preventDefault();held.add(d);highlight();sendCommand()}if(e.code==='Space'){e.preventDefault();stop()}});
window.addEventListener('keyup',e=>{const d=keymap[e.code];if(d){held.delete(d);highlight();sendCommand(true)}});
window.addEventListener('blur',neutral);document.addEventListener('visibilitychange',()=>{if(document.hidden)neutral()});
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.add(b.dataset.dir);highlight();sendCommand()});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{held.delete(b.dataset.dir);highlight();sendCommand(true)})});
setInterval(()=>sendCommand(),90);$('speed').oninput=()=>{$('speedValue').textContent=$('speed').value+' см/с'};
$('record').onclick=async()=>{const enabled=!state.recording;$('record').disabled=true;try{await api('record',{enabled});message(enabled?'Запись включена: полные данные сохраняются на роботе.':'Запись закрыта и сохранена на роботе.')}catch(e){message(e.message,true)}finally{$('record').disabled=false}};
$('markForm').onsubmit=async e=>{e.preventDefault();neutral();try{await api('mark',{label:$('markLabel').value});$('markLabel').value='';message('Сохранены точка наблюдения, время и свежий кадр.')}catch(e){message(e.message,true)}};
let markVersion='';
async function status(){try{const r=await fetch('/api/status',{signal:AbortSignal.timeout(1800)});if(!r.ok)throw Error();state=await r.json();$('connection').textContent='Робот на связи';$('connectionDot').classList.add('on');$('driveStatus').textContent=state.active?'Включён':state.ready?'Отключён':'STOP';$('armedBadge').textContent=state.active?'Включён':'Idle';$('poseStatus').textContent=state.pose_age!==null&&state.pose_age<.7?state.pose_source:'Нет свежей позы';$('lidarStatus').textContent=state.cloud_age!==null&&state.cloud_age<.7?state.cloud_hz+' Гц':'Нет данных';let v=Object.values(state.voltage||{});$('voltage').textContent=v.length?Math.min(...v.map(x=>x.value)).toFixed(1)+' В · '+Math.round(Math.max(...v.map(x=>x.age)))+' с назад':'После включения';$('recordStatus').textContent=state.recording?'● Идёт запись':'Выключена';$('recordDot').classList.toggle('on',state.recording);$('record').textContent=state.recording?'■ Завершить запись':'● Начать запись';$('session').textContent=state.session;$('cameraBadge').textContent=state.camera_age!==null&&state.camera_age<1?'640×480 · 5 Гц':'нет сигнала';$('cameraEmpty').textContent=cameraVisible?(state.camera_error||'Ожидаем кадр…'):'Камера скрыта';$('cameraEmpty').classList.toggle('hidden',cameraVisible&&state.camera_age!==null&&state.camera_age<1);$('camera').style.opacity=state.camera_age!==null&&state.camera_age<1?'1':'.25';$('arm').disabled=armBusy||state.active;$('axes').replaceChildren(...[0,1,2,3].map(n=>{const a=state.axes[String(n)],el=document.createElement('span');el.textContent=n+' · '+(!a||a.age>.7?'нет связи':a.error&&a.error!==2048?'ошибка '+a.error:a.state===8?'в работе':'Idle');return el}));const marks=state.marks||[];$('markCount').textContent=marks.length;const key=marks.map(m=>m.id).join();if(key!==markVersion){markVersion=key;$('marks').replaceChildren(...marks.slice().reverse().map(m=>{const row=document.createElement('div');row.className='mark-item';const a=document.createElement('span'),b=document.createElement('span');a.textContent=m.label;b.textContent=m.source+' · '+new Date(m.stamp*1000).toLocaleTimeString('ru-RU');row.append(a,b);return row}))}scheduleDraw()}catch(e){$('connection').textContent='Нет связи с GUI';$('connectionDot').classList.remove('on');state.active=false;held.clear();highlight()}finally{setTimeout(status,500)}}status();
async function cameraTick(){if(cameraVisible&&!document.hidden){try{const r=await fetch('/camera.jpg?t='+Date.now(),{signal:AbortSignal.timeout(2000)});if(r.ok){const blob=await r.blob(),u=URL.createObjectURL(blob),old=$('camera').src;$('camera').src=u;if(old.startsWith('blob:'))URL.revokeObjectURL(old)}}catch{}}setTimeout(cameraTick,220)}cameraTick();
$('cameraToggle').onclick=()=>{cameraVisible=!cameraVisible;$('camera').hidden=!cameraVisible;$('cameraToggle').textContent=cameraVisible?'◉':'○'};
document.querySelectorAll('.fullscreen').forEach(b=>b.onclick=()=>{const el=$(b.dataset.target);if(document.fullscreenElement)document.exitFullscreen();else el.requestFullscreen()});
// Small point-cloud renderer: perspective 3D, orbit, pinch/zoom. No CDN or GPU work on Pi.
const canvas=$('cloud'),ctx=canvas.getContext('2d');let az=Math.PI/2,el=.9,zoom=1.6,drawPending=false,pointers=new Map(),pinch=0;
function scheduleDraw(){if(!drawPending){drawPending=true;requestAnimationFrame(draw)}}
new ResizeObserver(scheduleDraw).observe(canvas);
function project(x,y,z){const u=Math.cos(az)*x-Math.sin(az)*y,d=Math.sin(az)*x+Math.cos(az)*y,vertical=Math.cos(el)*z+Math.sin(el)*d,depth=-Math.cos(el)*d+Math.sin(el)*z;const scale=Math.min(canvas.width,canvas.height)*.7*zoom/Math.max(1.8,6-depth);return [canvas.width*.5+u*scale,canvas.height*.55-vertical*scale,depth,scale]}
function line(a,b,color,width=1){const p=project(...a),q=project(...b);ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function local(p){if(!scenePose)return p;const x=p[0]-scenePose.x,y=p[1]-scenePose.y,a=scenePose.yaw;return [Math.cos(a)*x+Math.sin(a)*y,-Math.sin(a)*x+Math.cos(a)*y,(p[2]||0)-scenePose.z]}
function draw(){drawPending=false;const dpr=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.fillStyle='#0c111a';ctx.fillRect(0,0,w,h);for(let k=-4;k<=4;k+=.5){line([k,-4,-.045],[k,4,-.045],k===0?'#294254':'#192633',dpr*.7);line([-4,k,-.045],[4,k,-.045],k===0?'#294254':'#192633',dpr*.7)}const sorted=points.map(p=>({p,s:project(...p)})).sort((a,b)=>a.s[2]-b.s[2]);for(const {p,s} of sorted){const height=Math.max(0,Math.min(1,(p[2]+.045)/1.5)),hue=165-165*height;ctx.fillStyle=`hsl(${hue},65%,${52+height*12}%)`;const size=Math.max(1.4*dpr,Math.min(4*dpr,s[3]*.04));ctx.fillRect(s[0],s[1],size,size)}const trace=state.trace||[];for(let i=1;i<trace.length;i++)line(local(trace[i-1]),local(trace[i]),'#7f9ff080',1.5*dpr);for(const m of state.marks||[]){if(m.source!==state.pose_source)continue;const q=project(...local([m.pose.x,m.pose.y,m.pose.z]));ctx.beginPath();ctx.arc(q[0],q[1],4*dpr,0,Math.PI*2);ctx.fillStyle='#ffc977';ctx.fill()}const corners=[[-.17,-.19,0],[.17,-.19,0],[.17,.19,0],[-.17,.19,0]];ctx.beginPath();corners.forEach((p,i)=>{const q=project(...p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.closePath();ctx.fillStyle='#518df066';ctx.fill();ctx.strokeStyle='#8cb7ff';ctx.lineWidth=1.5*dpr;ctx.stroke();line([0,0,.05],[.5,0,.05],'#e7efff',2*dpr);line([.5,0,.05],[.37,.08,.05],'#e7efff',2*dpr);line([.5,0,.05],[.37,-.08,.05],'#e7efff',2*dpr)}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const p=[...pointers.values()];pinch=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1])}});
canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===1){az+=(e.clientX-old[0])*.008;el=Math.max(.12,Math.min(Math.PI/2,el+(e.clientY-old[1])*.008))}else{const p=[...pointers.values()],distance=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(pinch>0)zoom=Math.max(.45,Math.min(5,zoom*distance/pinch));pinch=distance}scheduleDraw()});
for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,e=>pointers.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(5,zoom*Math.exp(-e.deltaY*.001)));scheduleDraw()},{passive:false});$('topView').onclick=()=>{el=Math.PI/2;az=Math.PI/2;scheduleDraw()};$('resetView').onclick=()=>{az=Math.PI/2;el=.9;zoom=1.6;scheduleDraw()};
async function cloudTick(){if(!document.hidden){try{const r=await fetch('/api/cloud',{signal:AbortSignal.timeout(2000)}),j=await r.json();points=j.points||[];scenePose=j.pose;$('cloudInfo').textContent=j.stats?`${j.stats.shown.toLocaleString('ru-RU')} точек · ${j.stats.window ? 'накопление 1,5 с по LIO' : 'текущий кадр'} · исходный кадр ${j.stats.raw}`:'';$('cloudEmpty').classList.toggle('hidden',points.length>0&&j.age!==null&&j.age<.7);if(j.age===null||j.age>.7)points=[];scheduleDraw()}catch{}}setTimeout(cloudTick,250)}cloudTick();
