/* Saved-map view. Pointer placement creates annotations, never motion. */
(()=>{
const c=$('savedMap'),gl=c.getContext('webgl',{antialias:true});
if(!gl){$('mapStatus').textContent='Для карты нужен WebGL';return}
let az=Math.PI/2,el=.85,cx=0,cy=0,span=6,aspect=1,data=null,mode=null,drag=null,pending=null,mapState={},dirty=true;
const vs=`attribute vec3 p;attribute vec3 color;uniform vec2 center;uniform vec2 viewport;uniform float az;uniform float el;uniform float span;uniform float size;varying vec3 col;void main(){vec3 q=p-vec3(center,0.0);float u=cos(az)*q.x-sin(az)*q.y;float d=sin(az)*q.x+cos(az)*q.y;float v=cos(el)*q.z+sin(el)*d;float depth=-cos(el)*d+sin(el)*q.z;gl_Position=vec4(u*2.0/span, v*2.0/span*viewport.x/viewport.y,-depth/30.0,1.0);gl_PointSize=size;col=color;}`;
const fs=`precision mediump float;varying vec3 col;void main(){gl_FragColor=vec4(col,1.0);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,vs));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);
const attrs=['p','color'].map(x=>gl.getAttribLocation(pr,x)),uniforms={};for(const x of ['center','viewport','az','el','span','size'])uniforms[x]=gl.getUniformLocation(pr,x);
function buffer(points,color){const a=new Float32Array(points.length*6);points.forEach((p,i)=>{a.set(p,i*6);a.set(typeof color==='function'?color(p):color,i*6+3)});const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,a,gl.STATIC_DRAW);return {b,n:points.length}}
function paint(b,type,size=2){gl.bindBuffer(gl.ARRAY_BUFFER,b.b);attrs.forEach((a,i)=>{gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,24,i*12)});gl.uniform1f(uniforms.size,size);gl.drawArrays(type,0,b.n)}
let cloud,trace,grid;
function arrow(p,color){const length=.32,x=p.x,y=p.y,z=.1,a=p.yaw,ex=x+Math.cos(a)*length,ey=y+Math.sin(a)*length;return buffer([[x,y,z],[ex,ey,z],[ex,ey,z],[ex-.10*Math.cos(a-.6),ey-.10*Math.sin(a-.6),z],[ex,ey,z],[ex-.10*Math.cos(a+.6),ey-.10*Math.sin(a+.6),z]],color)}
function draw(){requestAnimationFrame(draw);if(!dirty||!data)return;dirty=false;const ratio=Math.min(devicePixelRatio,2);c.width=c.clientWidth*ratio;c.height=c.clientHeight*ratio;gl.viewport(0,0,c.width,c.height);gl.clearColor(.047,.067,.10,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.uniform2f(uniforms.center,cx,cy);gl.uniform2f(uniforms.viewport,c.width,c.height);gl.uniform1f(uniforms.az,az);gl.uniform1f(uniforms.el,el);gl.uniform1f(uniforms.span,span);paint(grid,gl.LINES,1);paint(cloud,gl.POINTS,2*ratio);gl.disable(gl.DEPTH_TEST);paint(trace,gl.LINE_STRIP,1);for(const g of mapState.goals||[]){const b=arrow(g,[1,.75,.3]);paint(b,gl.LINES);gl.deleteBuffer(b.b)}if(mapState.pose){const b=arrow(mapState.pose,[.3,1,.6]);paint(b,gl.LINES);gl.deleteBuffer(b.b)}if(state.navigation?.path?.length){const b=buffer(state.navigation.path,[1,.4,.3]);paint(b,gl.LINE_STRIP);gl.deleteBuffer(b.b)}if(pending){const b=arrow(pending,[1,.35,.6]);paint(b,gl.LINES);gl.deleteBuffer(b.b)}}requestAnimationFrame(draw);new ResizeObserver(()=>{const next=Math.max(1,c.clientWidth/c.clientHeight);span*=next/aspect;aspect=next;dirty=true}).observe(c);
function world(e){const r=c.getBoundingClientRect(),u=((e.clientX-r.left)/r.width-.5)*span,v=(.5-(e.clientY-r.top)/r.height)*span*r.height/r.width;return {x:cx+Math.cos(az)*u+Math.sin(az)*v,y:cy-Math.sin(az)*u+Math.cos(az)*v}}
function choose(m){mode=m;pending=null;el=Math.PI/2;az=Math.PI/2;dirty=true;$('mapApply').disabled=true;for(const [id,key]of [['mapPose','pose'],['mapGoal','goal']])$(id).classList.toggle('selected',m===key);$('mapHelp').textContent=m==='pose'?'Укажи центр робота и протяни стрелку, куда он смотрит. Для применения привод должен быть в STOP.':'Укажи цель и протяни стрелку нужного направления. После применения цель появится в списке.'}
$('mapPose').onclick=()=>choose('pose');$('mapGoal').onclick=()=>choose('goal');$('mapTop').onclick=()=>{el=Math.PI/2;az=Math.PI/2;dirty=true};$('mapOrbit').onclick=()=>{mode=null;el=.85;dirty=true};
c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,start:world(e)};if(mode){pending={...drag.start,yaw:0};dirty=true}};
c.onpointermove=e=>{if(!drag)return;if(mode){const p=world(e);pending.yaw=Math.atan2(p.y-pending.y,p.x-pending.x);$('mapApply').disabled=false}else if(e.shiftKey){const old=world({clientX:drag.x,clientY:drag.y}),now=world(e);cx+=old.x-now.x;cy+=old.y-now.y}else{az+=(e.clientX-drag.x)*.008;el=Math.max(.15,Math.min(Math.PI/2,el+(e.clientY-drag.y)*.008))}drag.x=e.clientX;drag.y=e.clientY;dirty=true};
c.onpointerup=()=>{drag=null;if(pending)$('mapApply').disabled=false};c.onpointercancel=()=>{drag=null};c.addEventListener('wheel',e=>{e.preventDefault();span=Math.max(1,Math.min(25,span*Math.exp(e.deltaY*.001)));dirty=true},{passive:false});
$('mapApply').onclick=async()=>{if(!pending||!mode)return;try{await api('map/'+mode,pending);message(mode==='pose'?'Положение задано вручную. Нажми «Уточнить по лидару».':'Цель сохранена.');pending=null;$('mapApply').disabled=true;dirty=true}catch(e){message(e.message,true)}};
$('mapRefine').onclick=async()=>{const b=$('mapRefine');b.disabled=true;try{const r=await api('map/refine');message(`Совмещение: ${(r.quality.overlap*100).toFixed(0)}% точек, RMS ${(r.quality.rms*100).toFixed(1)} см`)}catch(e){message(e.message,true)}finally{b.disabled=false}};
let keys='';setInterval(()=>{mapState=state.map||{};dirty=true;const p=mapState.pose,q=mapState.quality;$('mapStatus').textContent=p?`Робот: x ${p.x.toFixed(2)} · y ${p.y.toFixed(2)} м · ${q?.method||''}. ${state.navigation?.message||'Цель не задана'}.`:'Робот не привязан к карте. Укажи положение и направление.';const key=JSON.stringify(mapState.goals);if(key===keys)return;keys=key;$('mapGoals').replaceChildren(...(mapState.goals||[]).map(g=>{const row=document.createElement('span'),go=document.createElement('button'),del=document.createElement('button');go.textContent=`${g.label} (${g.x.toFixed(1)}, ${g.y.toFixed(1)}) → ехать`;go.onclick=async()=>{go.disabled=true;try{await api('map/navigate',{id:g.id});message('Навигационная цель отправлена')}catch(e){message(e.message,true)}finally{go.disabled=false}};del.textContent='×';del.title='Удалить цель';del.onclick=()=>api('map/remove',{id:g.id}).catch(e=>message(e.message,true));row.append(go,del);return row}))},700);
fetch('/api/map').then(r=>{if(!r.ok)throw Error('Карта ещё не загружена');return r.json()}).then(j=>{data=j;cx=(j.bounds[0][0]+j.bounds[1][0])/2;cy=(j.bounds[0][1]+j.bounds[1][1])/2;span=Math.max(j.bounds[1][0]-j.bounds[0][0],j.bounds[1][1]-j.bounds[0][1])*1.35*Math.max(1,c.clientWidth/c.clientHeight);cloud=buffer(j.points,p=>{if(p[2]<.10)return [.13,.21,.24];const h=Math.max(0,Math.min(1,p[2]/1.5));return [.35+.4*h,.65-.1*h,.65-.3*h]});trace=buffer(j.trajectory,[.2,.9,.85]);const lines=[];for(let x=Math.floor(j.bounds[0][0]);x<=j.bounds[1][0];x+=.5)lines.push([x,j.bounds[0][1],0],[x,j.bounds[1][1],0]);for(let y=Math.floor(j.bounds[0][1]);y<=j.bounds[1][1];y+=.5)lines.push([j.bounds[0][0],y,0],[j.bounds[1][0],y,0]);grid=buffer(lines,[.15,.2,.25]);dirty=true}).catch(e=>$('mapStatus').textContent=e.message);
})();
