'use strict';
const $=id=>document.getElementById(id), tab=crypto.randomUUID();
let held=false, armed=false, seq=0, inFlight=0, x=0,y=0, holdGeneration=0, lease='', loggedIn=false;
const driveKeys=new Set(), directionCodes=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight'];
function keyboardDirection(){y=Number(driveKeys.has('KeyW')||driveKeys.has('ArrowUp'))-Number(driveKeys.has('KeyS')||driveKeys.has('ArrowDown'));x=Number(driveKeys.has('KeyD')||driveKeys.has('ArrowRight'))-Number(driveKeys.has('KeyA')||driveKeys.has('ArrowLeft'));const radius=$('joystick').getBoundingClientRect().width/2-30,scale=Math.max(1,Math.hypot(x,y));$('knob').style.transform=`translate(${x*radius/scale}px,${-y*radius/scale}px)`;}
window.addEventListener('keydown',e=>{if(directionCodes.includes(e.code)&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();if(!held)return;driveKeys.add(e.code);keyboardDirection();}});
window.addEventListener('keyup',e=>{if(directionCodes.includes(e.code)){e.preventDefault();driveKeys.delete(e.code);if(held)keyboardDirection();}});
async function api(op,data={}){
 const controller=new AbortController(), timer=setTimeout(()=>controller.abort(),700);
 try{const r=await fetch('/api/'+op,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,tab}),signal:controller.signal});const b=await r.json();if(!r.ok)throw Error(b.error||b.message||'Запрос отклонён');return b;}finally{clearTimeout(timer);}
}
function note(text){$('message').textContent=text;}
function release(emergency=false){const wasActive=held||armed;held=false;armed=false;holdGeneration++;driveKeys.clear();x=y=0;$('knob').style.transform='';$('deadman').classList.remove('held');$('deadman').textContent='Включить управление';$('deadman').setAttribute('aria-pressed','false');if(wasActive||emergency)fetch('/api/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tab,lease,emergency}),keepalive:true}).catch(()=>{});}
$('login').onsubmit=async e=>{e.preventDefault();try{await api('login',{password:$('password').value});loggedIn=true;$('password').value='';$('login').hidden=true;$('controls').hidden=false;note('Управление готово. Движение пока выключено.');}catch(e){note(e.message);}};
async function enableControl(){if(held||$('deadman').disabled||!loggedIn)return;x=y=0;driveKeys.clear();$('knob').style.transform='';held=true;const generation=++holdGeneration;$('deadman').classList.add('held');$('deadman').textContent='Выключить управление';$('deadman').setAttribute('aria-pressed','true');try{const result=await api('arm');if(!held||generation!==holdGeneration){release();return;}lease=result.lease;seq=0;armed=true;}catch(e){release();note(e.message);}}
$('deadman').onclick=()=>{if(held)release();else enableControl();$('deadman').blur();};
window.addEventListener('keydown',e=>{if(e.code==='Space')e.preventDefault();if(e.code==='Escape'){e.preventDefault();release(true);}});
window.addEventListener('keyup',e=>{if(e.code==='Space')e.preventDefault();});
let joystickPointer=null;
function move(e){if(e.pointerId!==joystickPointer)return;const r=$('joystick').getBoundingClientRect(), radius=r.width/2-30;let dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2;const scale=Math.max(1,Math.hypot(dx,dy)/radius);dx/=scale;dy/=scale;x=dx/radius;y=-dy/radius;$('knob').style.transform=`translate(${dx}px,${dy}px)`;}
$('joystick').onpointerdown=e=>{e.preventDefault();joystickPointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);move(e);};
$('joystick').onpointermove=move;
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,()=>{joystickPointer=null;x=y=0;$('knob').style.transform='';});
for(const [id,turn] of [['turn-left',-1],['turn-right',1]]){const button=$(id);let pointer=null;button.onpointerdown=e=>{e.preventDefault();if(!held)return;pointer=e.pointerId;button.setPointerCapture(pointer);y=0;x=turn;};for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>{if(e.pointerId!==pointer)return;pointer=null;x=y=0;});}
$('stop').onclick=()=>release(true);
$('reset').onclick=async()=>{release();try{note((await api('reset')).message);}catch(e){note(e.message);}};
window.addEventListener('pagehide',()=>release());document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});
setInterval(()=>{if(!held||!armed||inFlight>=3)return;const rpm=Number($('speed').value);if(!Number.isFinite(rpm)||rpm<0){release();note('Укажи неотрицательную скорость');return;}const v=rpm/60*2*Math.PI*.045,scale=Math.max(1,Math.abs(y)+Math.abs(x)),commandSeq=++seq,commandGeneration=holdGeneration;inFlight++;api('command',{lease,seq:commandSeq,linear:y*v/scale,angular:-x*2*v/.29174/scale}).catch(e=>{if(commandGeneration===holdGeneration&&commandSeq===seq){release();note(e.message);}}).finally(()=>inFlight--);},50);
setInterval(()=>{$('speed').disabled=held;},50);
async function refresh(){const requestGeneration=holdGeneration,wasArmed=armed;try{const r=await fetch('/api/status',{signal:AbortSignal.timeout(900)});if(!r.ok){if(held)release();loggedIn=false;$('login').hidden=false;$('controls').hidden=true;note('Войди в пульт. После перезапуска сервиса вход требуется заново.');return;}loggedIn=true;const s=await r.json();$('login').hidden=true;$('controls').hidden=false;$('state').textContent=s.state;$('reason').textContent=s.reason;$('deadman').disabled=!s.motion_enabled||s.state==='FAULT';if(wasArmed&&armed&&requestGeneration===holdGeneration&&!['ARMING','RUNNING'].includes(s.state))release();$('axes').replaceChildren();const names={0:'Заднее правое',1:'Заднее левое',2:'Переднее левое',3:'Переднее правое'};for(const [n,a]of Object.entries(s.axes)){const c=document.createElement('div');c.className='card';const h=document.createElement('h3');h.textContent=`${names[n]} · CAN ${n}`;c.append(h);for(const text of [`${a.state===1?'Idle':a.state===8?'Управление':'Состояние '+a.state} · ${a.error===2048?'ожидание команд':a.error?'ошибка '+a.error:'без ошибок'}`,`Команда ${a.target_rpm.toFixed(1)} об/мин`,`Hall ${a.count??'—'} · связь ${a.heartbeat_age.toFixed(2)} с`,`${a.voltage?.toFixed(1)??'—'} В · ${a.current?.toFixed(2)??'—'} А`]){const p=document.createElement('p');p.textContent=text;c.append(p);}$('axes').append(c);}note(s.motion_enabled?'Локальный пульт. Держи аппаратное отключение рядом.':'Движение заблокировано до проверки безопасности.');}catch(e){note('Нет ответа на запрос состояния; команды контролирует таймаут CAN-моста.');}}
setInterval(()=>{if(loggedIn)refresh();},500);refresh();
